#!/bin/bash

echo "deploying..."

source $OPENSHIFT_PHP_DIR/lib/util
export PATH=${OPENSHIFT_PHP_DIR}usr/bin:/bin:/usr/bin:/usr/sbin

cp $OPENSHIFT_REPO_DIR/env $OPENSHIFT_REPO_DIR/Cachet/.env

# set environment variables
echo "$OPENSHIFT_MYSQL_DB_HOST" > ~/.env/user_vars/DB_HOST
echo "$OPENSHIFT_APP_NAME" > ~/.env/user_vars/DB_DATABASE
echo "$OPENSHIFT_MYSQL_DB_USERNAME" > ~/.env/user_vars/DB_USERNAME
echo "$OPENSHIFT_MYSQL_DB_PASSWORD" > ~/.env/user_vars/DB_PASSWORD
echo "$OPENSHIFT_MYSQL_DB_PORT" > ~/.env/user_vars/DB_PORT

DB_HOST=$OPENSHIFT_MYSQL_DB_HOST
DB_DATABASE=$OPENSHIFT_APP_NAME
DB_USERNAME=$OPENSHIFT_MYSQL_DB_USERNAME
DB_PASSWORD=$OPENSHIFT_MYSQL_DB_PASSWORD
DB_PORT=$OPENSHIFT_MYSQL_DB_PORT


# both nginx and phpfpm configs are rebuilt every deploy
build_nginx_config & build_phpfpm_config

# get cachet if doesn't exist
if [ ! -d $OPENSHIFT_REPO_DIR/Cachet ]; then
        cd $OPENSHIFT_REPO_DIR
        git clone https://github.com/cachethq/Cachet.git Cachet
else
	cp $OPENSHIFT_REPO_DIR/Cachet/composer.json.orig $OPENSHIFT_REPO_DIR/Cachet/composer.json
	cp $OPENSHIFT_REPO_DIR/Cachet/composer.lock.orig $OPENSHIFT_REPO_DIR/Cachet/composer.lock
        cd $OPENSHIFT_REPO_DIR/Cachet
        git pull
fi

# replace php-apcu with php-apc
cp $OPENSHIFT_REPO_DIR/Cachet/composer.json $OPENSHIFT_REPO_DIR/Cachet/composer.json.orig
cp $OPENSHIFT_REPO_DIR/Cachet/composer.lock $OPENSHIFT_REPO_DIR/Cachet/composer.lock.orig
sed -i s/ext-apcu/ext-apc/g $OPENSHIFT_REPO_DIR/Cachet/composer.json
sed -i s/ext-apcu/ext-apc/g $OPENSHIFT_REPO_DIR/Cachet/composer.lock

# install/update composer
cd ${OPENSHIFT_DATA_DIR}
if [ ! -f "${OPENSHIFT_DATA_DIR}/composer" ]; then
	wget https://getcomposer.org/installer
	LD_LIBRARY_PATH=${OPENSHIFT_PHP_DIR}usr/bin  ${OPENSHIFT_PHP_DIR}usr/bin/hhvm  --config ${OPENSHIFT_REPO_DIR}config/hhvm.d/config.ini installer --filename=composer
	rm installer
else
    LD_LIBRARY_PATH=${OPENSHIFT_PHP_DIR}usr/bin  ${OPENSHIFT_PHP_DIR}usr/bin/hhvm  --config ${OPENSHIFT_REPO_DIR}config/hhvm.d/config.ini ${OPENSHIFT_DATA_DIR}/composer self-update

fi

# Setup Cachet
cd $OPENSHIFT_REPO_DIR/Cachet
cp $OPENSHIFT_REPO_DIR/env $OPENSHIFT_REPO_DIR/Cachet/.env
php ${OPENSHIFT_DATA_DIR}composer install --no-dev -o
php artisan migrate
php artisan key:generate
