#!/bin/bash

echo "deploying..."

source $OPENSHIFT_PHP_DIR/lib/util

# both nginx and phpfpm configs are rebuilt every deploy
build_nginx_config & build_phpfpm_config

# get cachet if doesn't exist
if [ ! -d $OPENSHIFT_REPO_DIR/Cachet ]; then
        cd $OPENSHIFT_REPO_DIR
        git clone https://github.com/cachethq/Cachet.git Cachet
else
        cd $OPENSHIFT_REPO_DIR/Cachet
        git pull
fi

# install/update composer
#cd ${OPENSHIFT_HOMEDIR}/cachet-hhvm/usr/bin/
#if [ ! -f "${OPENSHIFT_DATA_DIR}/composer" ]; then
#	curl -s https://getcomposer.org/installer | ${OPENSHIFT_HOMEDIR}/cachet-hhvm/usr/bin/hhvm -- --install-dir=$OPENSHIFT_DATA_DIR --filename=composer
#else
#    ${OPENSHIFT_HOMEDIR}/cachet-hhvm/usr/bin/hhvm ${OPENSHIFT_DATA_DIR}/composer self-update
#
#fi
