#!/bin/bash

echo "deploying..."

source $OPENSHIFT_PHP_DIR/lib/util

# both nginx and phpfpm configs are rebuilt every deploy
build_nginx_config & build_phpfpm_config

# get cachet if doesn't exist
if [ ! -d $OPENSHIFT_REPO_DIR/Cachet ]; then
        cd $OPENSHIFT_REPO_DIR
        git clone https://github.com/cachethq/Cachet.git Cachet
else
        cd $OPENSHIFT_REPO_DIR/Cachet
        git pull
fi

# replace php-apcu with php-apc
sed -i s/php-apcu/php-apc/g $OPENSHIFT_REPO_DIR/Cachet/composer.json
sed -i s/php-apcu/php-apc/g $OPENSHIFT_REPO_DIR/Cachet/composer.lock

# install/update composer
cd ${OPENSHIFT_DATA_DIR}
if [ ! -f "${OPENSHIFT_DATA_DIR}/composer" ]; then
	wget https://getcomposer.org/installer
	LD_LIBRARY_PATH=${OPENSHIFT_PHP_DIR}usr/bin  ${OPENSHIFT_PHP_DIR}usr/bin/hhvm  --config ${OPENSHIFT_REPO_DIR}config/hhvm.d/config.ini installer --filename=composer
	rm installer
else
    LD_LIBRARY_PATH=${OPENSHIFT_PHP_DIR}usr/bin  ${OPENSHIFT_PHP_DIR}usr/bin/hhvm  --config ${OPENSHIFT_REPO_DIR}config/hhvm.d/config.ini ${OPENSHIFT_DATA_DIR}/composer self-update

fi

# Setup Cachet
cd $OPENSHIFT_REPO_DIR/Cachet
php ${OPENSHIFT_DATA_DIR}composer install --no-dev -o
